test_format = 1.0

[default]
    args.is_public = 0
    args.install.init_main_permission="all_users"

    [default.curl_tests]
    #dash.path = "/"
    dash.logged_on_sso = true
    dash.expect_return_code= 401
    # ------------
    # Tests to run
    # ------------
